
name: Build and push

on: 
  push:
      branches:
      - 'main'
  schedule:
  - cron: "0 */24 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    name: ğŸƒâ€â™‚ï¸ Build container
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ’» Checkout code
      uses: actions/checkout@v3
    - name: â¬ Update Readme.md and description
      uses: meeDamian/sync-readme@v1.0.6
      with:
        user: ${{ secrets.DOCKER_HUB_USERNAME }}
        pass: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        slug: als3bas/zulu-purpurmc
        readme: ./README.md
        description: Minecraft 1.19 Server Running on PurpurMC and Zulu OpenJDK.
    - name: ğŸ“¦ Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: ğŸ“¦ Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: ğŸ” Login to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: ğŸ“¦ Build and push
      uses: docker/build-push-action@v3
      with: 
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: als3bas/zulu-purpurmc:latest,als3bas/zulu-purpurmc:1.19