name: ğŸ‘©ğŸ»â€ğŸ”¬ Build and push (Preview Version)

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: ğŸƒâ€â™‚ï¸ Build container
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ vars.MC_VERSION_PRE != 'NA' }}

    steps:
      - name: ğŸ‘©ğŸ»â€ğŸ”¬ Checkout code - Experimental Branch
        uses: actions/checkout@v3
      - name: ğŸ“¦ Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: ğŸ“¦ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: ğŸ” Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: ğŸ“¦ Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: als3bas/zulu-purpurmc:preview,als3bas/zulu-purpurmc:${{ vars.MC_VERSION_PRE }}-preview
          build-args: MC_VERSION=${{ vars.MC_VERSION_PRE }}
